### PR TITLE
Upgrade to support django 4

### PR DESCRIPTION
**Pull request by aksharahegde**
[Fixed. middleware backward competibility](https://github.com/vvangelovski/django-audit-log/commit/6b42216759c7b6add1c467c322950481cbaaa975)
[fix(models) on_delete error in AuthStampModel](https://github.com/vvangelovski/django-audit-log/commit/452e31fe8634b92d69b74588f47003a816136d46)
[fix(package) curry import error](https://github.com/vvangelovski/django-audit-log/commit/1311734d9c53f512bf5df7cca51fe221bfb3b312)

### CODE REVIEW

**Comment by Djones4822** [comment]
Will be testing this for a new 4.2x project, will report any issues

**Comment by Djones4822** [comment]
Not sure why the last commits reverted the ugettext change. Django deprecated ugettext in 2.2, I believe, and fully dropped it in 3.0 - definitely incompatible with 4.0 For backwards compatibility with <3.0 we could probably add an import check and an alias. 

Otherwise haven't really gotten to test it much yet, hoping to put it through its paces soon though.

**Comment by aksharahegde** [comment]
hey @Djones4822 .
something got messed up. I will update the PR by weekend. Thank you.

**Comment by aksharahegde** [comment]
fixed the mess that happened with gettext_lazy and ugettext_lazy imports.
Its working now.

**Pull request closed without merging**
